spring.application.name=backend
server.servlet.context-path=/api/v1

spring.datasource.url=jdbc:postgresql://localhost:6000/novafiscal
spring.datasource.username=novafiscal
spring.datasource.password=novafiscal

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true